export * from "./auth.service.ts";
export * from "./group.service.ts";
export * from "./course.service.ts";
export * from "./student.service.ts";
export * from "./branch.service.ts";
export * from "./teacher.service.ts";
export * from "./room.service.ts";
export * from "./general.service.ts";
export * from "./admin.service.ts";
